while true do
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")
    print("Crash is working")

    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
    Instance.new("Part")
end
